### PR TITLE
Update glpk interface for glpk >= 4.48.

### PR DESCRIPTION
**Pull request by jamesjer**
Regarding issue 118, here is an update to the glpk code.  It completely drops support for glpk < 4.48, which should be okay considering how old that release is.  I'm sure this can be improved, but it's a start.

### CODE REVIEW

**Comment by svigerske** [comment]
Did unit tests pass? Does the GMPL-interface in CoinUtils work with current Glpk, too? Will someone update ThirdParty/Glpk or do we drop that? (I think @LouHafer had quite some issues trying to adapt ThirdParty/Glpk for use with the updated buildtools/autotools setup and it might be ok to just drop it.)

**Comment by mjsaltzman** [comment]
Sorry, haven't quite gotten to this review yet. It's on my list.

On Thu, 2019-04-04 at 19:56 -0700, Stefan Vigerske wrote:
> Did unit tests pass? Does the GMPL-interface in CoinUtils work with
> current Glpk, too? Will someone update ThirdParty/Glpk or do we drop
> that? (I think @LouHafer had quite some issues trying to adapt
> ThirdParty/Glpk for use with the updated buildtools/autotools setup
> and it might be ok to just drop it.)
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Matthew Saltzman
School of Mathematical and Statistical Sciences
Clemson University
mjs AT clemson DOT edu

**Comment by mjsaltzman** [comment]
Unit tests passed for me. Note that 4.48 is from 2013. Latest is 2.65,
from Feb. 2018. Some things in later versions are quite different. For
example, the file that little patch applies to is no longer in the
sources.

Ted says that bringing glpk current would require updating SYMPHONY and
CBC as well.

On Thu, 2019-04-04 at 19:56 -0700, Stefan Vigerske wrote:
> Did unit tests pass? Does the GMPL-interface in CoinUtils work with
> current Glpk, too? Will someone update ThirdParty/Glpk or do we drop
> that? (I think @LouHafer had quite some issues trying to adapt
> ThirdParty/Glpk for use with the updated buildtools/autotools setup
> and it might be ok to just drop it.)
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or mute the thread.
-- 
Matthew Saltzman
School of Mathematical and Statistical Sciences
Clemson University
mjs AT clemson DOT edu

**Comment by mjsaltzman** [comment]
Oops. Latest is 4.65.

**Comment by tkralphs** [comment]
Unit tests passed with what version of Glpk? Do we have an updated ThirdParty package? My only comment was just that if we don't update SYMPHONY and Cbc, then they will be using a different version of Glpk than Osi, which will make life difficult. We can certainly either create a new branch of Osi with this support in it that can be checked out by those who are interested or we can make sure that we make the upgrade backward compatible by just putting #defines around the code that changes.

**Comment by jamesjer** [comment]
I built this with glpk 4.65.  It's entirely possible that >= 4.48 is too liberal, and it should really be >= some larger number.  SYMPHONY seems to build just fine with glpk 4.65.  I don't understand what is going on with Cbc and glpk, though.  The code refers to external variables named cbc_glp_tran and cbc_glp_prob, which don't seem to be defined or initialized anywhere.

**Comment by svigerske** [comment]
Assigned to @LouHafer, as he worked on the same in branch autotools-update.

**Comment by tkralphs** [comment]
If I'm not mistaken, the `master` branch is updated to the latest Glpk. @LouHafer is this true?

**Comment by LouHafer** [comment]
The OsiGlpk update to 4.65 is commit 505eef2 in the autotools-update branch of OsiGlpk, but I can't quickly convince myself it's been merged into trunk. @svigerske  or @tkralphs , maybe you know this off the top of your head. I'll try to make time the next few days to figure it out. My local environment is horribly out-of-date due to all the activity the last few months while I've been otherwise occupied.

**Comment by svigerske** [comment]
Yes, your updates have been merged into master.

This MR is mainly still open because we were hoping that you or Matt would look at the changes proposed here and see if there is anything you might have missed.

**Comment by LouHafer** [comment]
@svigerske, my memory is that I reconciled my changes with the changes in @jamesjer's code, so all changes are covered or I had some reason for not doing it / doing it differently. Give me a few days to see if I can find my notes --- there's a decent chance they'll turn up as I update my working environment.

**Comment by LouHafer** [comment]
@svigerske, @tkralphs, @mjsaltzman : I can't find my notes from the initial conversion, so I diff'd the current version against @jamesjer's. Here's the summary. The big change in the update is that glpk control parameters went into a couple of structures (smcp for simplex, iocp for integer optimisation) instead of the previous use of a bunch of different parameter setting methods. If you look at a the diff of the current OGSI.cpp against jj's, you'll quickly see that the majority of the diff output is just textual change. There are a few nontrivial differences.

jj's conversion put glpk.h bare into OGSI.hpp, which isn't our convention. So there are differences to keep detailed knowledge of glpk.h restricted to OGSI.cpp. Stefan already caught my failure to properly cast the control structures before delete in the destructor. I removed some code in getColLower, setColUpper,  and setColLower that forced -inf to 0 and inf to 0, then set it right back. Seems to be a vestige of much earlier bad behaviour by glpk. In loadProblem, I opted to not reinitialise the control structures, just set the fields OSI knows about. An arguable choice. Reinitialise and then reset might be better, but I was sort of allowing that someone who knew glpk might tweak them.

Neither jj or I dealt with the more exotic return codes in branchAndBound. A few could probably be handled in ways OSI would understand. Arguably the rest should just go to a result of abandoned.

Probably safe to close this, in my opinion.

**Comment by svigerske** [comment]
If you think that it could be closed, then please do so.

**Comment by LouHafer** [comment]
Actually doing the merge would be counterproductive, so closed with no further action.

**Pull request closed without merging**
